name: .NET

on:
  workflow_dispatch:
  schedule:
  #Run each day at 23:15
    - cron: '15 23 * * *'
  pull_request:
    branches: [ "main" ]

jobs:
  tests_unitAndUi:
    name: Unit and UI tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore ./PlaywrightAutomation.sln

    - name: Override config parameters
      shell: pwsh
      run: |
        Try
          {
            $configPath = './PlaywrightAutomation/appsettings.json'
            $jsonConfig = Get-Content $configPath | Out-String | ConvertFrom-Json
            $jsonConfig.Browser_Headless = 'true'
            $jsonConfig | ConvertTo-Json -depth 100 | Out-File $configPath
          }
          Catch
          {
            throw "$_.Exception.ToString()"
          }

    - name: Build
      run: dotnet build ./PlaywrightAutomation.sln --no-restore
      

    - name: Unit tests
      id: unitTests
      run: dotnet test ./PlaywrightAutomation.sln --filter "TestCategory=OnBuild" --no-build --verbosity normal
      
    # Slack message of Unit tests fail  
    - name: Slack Notification for Unit tests
      if: ${{ steps.unitTests.outcome == 'failure' && failure() }} 
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: Tests execution report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: autotest_boilerplates
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        SLACK_TITLE: .Net Unit tests (PW + .Net)
        MSG_MINIMAL: true
        SLACK_FOOTER: boilerplate
        
    - name: Run Playwright installation
      if: ${{ steps.unitTests.outcome == 'success' }} 
      shell: pwsh
      run: pwsh -Command "./PlaywrightAutomation/bin/Debug/net6.0/playwright.ps1 install"
    
    - name: UI tests
      if: ${{ steps.unitTests.outcome == 'success' }} 
      run: dotnet test ./PlaywrightAutomation.sln --filter "TestCategory!=OnBuild&TestCategory!=NotRun"
      
    - name: Slack Notification
      if: ${{ steps.unitTests.outcome == 'success' && failure() }} 
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_USERNAME: Tests execution report
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_CHANNEL: autotest_boilerplates
        SLACK_COLOR: ${{ job.status }}
        SLACK_MESSAGE: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        SLACK_TITLE: .Net UI tests
        MSG_MINIMAL: true
        SLACK_FOOTER: boilerplate
        